import React, { createContext, useContext } from "react";
import { Audio } from "@remotion/media";
import { AbsoluteFill, interpolate, Sequence, staticFile, useCurrentFrame, useVideoConfig } from "remotion";
import type { TransitionPresentation, TransitionPresentationComponentProps } from "@remotion/transitions";
import { body, C, display, gradientText } from "../theme";
import { EXPO_IN, F_QUICK, F_STAGGER, F_STD, pop, punch, PUSH_IN } from "./theme";

// ── Sound ────────────────────────────────────────────────────────────────────
// Remotion's hosted SFX set (see .claude/skills/remotion-best-practices/remotion-markup/sfx.md).
export const SFX = {
  whoosh: "https://remotion.media/whoosh.wav",
  click: "https://remotion.media/mouse-click.wav",
  toggle: "https://remotion.media/switch.wav",
  ding: "https://remotion.media/ding.wav",
} as const;

/** Set to false to render without the hosted SFX (e.g. offline). */
export const SFX_ENABLED = true;

/**
 * Audio gate. A scene rendered twice (the vertical cut shows two regions of one scene) must
 * play its voice and SFX once: the second copy is wrapped in `<AudioOn.Provider value={false}>`.
 */
export const AudioOn = createContext(true);

export const Sfx: React.FC<{ at: number; src: string; volume?: number }> = ({ at, src, volume = 0.4 }) => {
  const { fps } = useVideoConfig();
  const audioOn = useContext(AudioOn);
  if (!SFX_ENABLED || !audioOn) return null;
  return (
    <Sequence from={at} durationInFrames={2 * fps} layout="none" name="sfx">
      <Audio src={src} volume={volume} />
    </Sequence>
  );
};

/**
 * One voiceover line, from public/vo/beat-N.wav (generated by tools/make_vo.py).
 * `file` (a path under public/, e.g. "vo/clip-chat.wav") overrides the beat — the feature clips
 * reuse the overview scenes with their own line.
 */
export const Vo: React.FC<{ beat: number; at?: number; file?: string }> = ({ beat, at = 6, file }) => {
  const audioOn = useContext(AudioOn);
  if (!audioOn) return null;
  return (
    <Sequence from={at} layout="none" name={file ?? `vo ${beat}`}>
      <Audio src={staticFile(file ?? `vo/beat-${beat}.wav`)} volume={1} />
    </Sequence>
  );
};

// ── Camera ───────────────────────────────────────────────────────────────────
/** Slow push-in across the whole scene: scale 1 → 1.04. */
export const PushIn: React.FC<{ duration: number; children: React.ReactNode }> = ({ duration, children }) => {
  const frame = useCurrentFrame();
  return (
    <AbsoluteFill
      style={{
        scale: interpolate(frame, [0, duration], [1, PUSH_IN], { extrapolateLeft: "clamp", extrapolateRight: "clamp" }),
      }}
    >
      {children}
    </AbsoluteFill>
  );
};

// ── Kinetic type ─────────────────────────────────────────────────────────────
/**
 * Word-by-word punch-in. Mark accent words with *asterisks*: they get the brand gradient,
 * a spring pop (the hero overshoot) and a brief glow flash. Plain words rise with ease-out-expo.
 */
export const PunchLine: React.FC<{
  text: string;
  at: number;
  size: number;
  color?: string;
  weight?: number;
  align?: React.CSSProperties["textAlign"];
}> = ({ text, at, size, color = C.fg, weight = 800, align = "left" }) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  // Accent spans may cover several words: "*Your rules.*" opens on the first word, closes on the last.
  let open = false;
  const words = text.split(" ").map((raw) => {
    const starts = raw.startsWith("*");
    const accent = open || starts;
    open = (open || starts) && !raw.endsWith("*");
    return { word: raw.replace(/\*/g, ""), accent };
  });
  return (
    <div style={{ fontFamily: display, fontSize: size, fontWeight: weight, lineHeight: 1.08, color, textAlign: align }}>
      {words.map(({ word, accent }, i) => {
        const start = at + i * F_STAGGER;
        const p = punch(frame, start, F_STD);
        const s = accent ? pop(frame, start, fps) : interpolate(p, [0, 1], [0.7, 1]);
        const flash = accent
          ? interpolate(frame, [start + 3, start + 8, start + 16], [0, 1, 0], {
              extrapolateLeft: "clamp",
              extrapolateRight: "clamp",
            })
          : 0;
        return (
          <span
            key={i}
            style={{
              display: "inline-block",
              marginRight: "0.24em",
              opacity: p,
              translate: `0px ${(1 - p) * 0.45 * size}px`,
              scale: s,
              filter: flash ? `drop-shadow(0 0 ${18 * flash}px hsl(239 100% 82% / ${0.9 * flash}))` : undefined,
              ...(accent ? gradientText : {}),
            }}
          >
            {word}
          </span>
        );
      })}
    </div>
  );
};

/** Left-column caption for feature scenes: flashing eyebrow, punched headline lines, fast sub. */
export const ECaption: React.FC<{ eyebrow: string; lines: string[]; sub: string; at?: number }> = ({
  eyebrow,
  lines,
  sub,
  at = 2,
}) => {
  const frame = useCurrentFrame();
  const e = punch(frame, at, F_QUICK);
  let offset = at + 2;
  const subAt = at + 2 + lines.join(" ").split(" ").length * F_STAGGER + 2;
  return (
    <div style={{ position: "absolute", left: 130, top: 300, width: 700 }}>
      <div
        style={{
          fontFamily: body,
          fontSize: 22,
          fontWeight: 700,
          letterSpacing: 4,
          textTransform: "uppercase",
          color: C.primary,
          marginBottom: 20,
          opacity: e,
          translate: `${(1 - e) * -30}px 0px`,
        }}
      >
        {eyebrow}
      </div>
      {lines.map((l) => {
        const node = <PunchLine key={l} text={l} at={offset} size={70} />;
        offset += l.split(" ").length * F_STAGGER;
        return node;
      })}
      <div
        style={{
          fontFamily: body,
          fontSize: 28,
          lineHeight: 1.4,
          color: C.muted,
          marginTop: 26,
          opacity: punch(frame, subAt, F_STD),
          translate: `0px ${(1 - punch(frame, subAt, F_STD)) * 20}px`,
        }}
      >
        {sub}
      </div>
    </div>
  );
};

/** Panel that pops in with expo + a faint overshoot on scale. */
export const EPanel: React.FC<{ at: number; style?: React.CSSProperties; children: React.ReactNode }> = ({
  at,
  style,
  children,
}) => {
  const frame = useCurrentFrame();
  const p = punch(frame, at, F_STD);
  return (
    <div
      style={{
        position: "absolute",
        background: `linear-gradient(180deg, ${C.cardRaised}, ${C.card})`,
        border: `1px solid ${C.border}`,
        borderRadius: 24,
        boxShadow: `0 30px 80px hsl(240 80% 3% / ${0.7 * p}), inset 0 1px 0 hsl(226 60% 97% / 0.05)`,
        opacity: p,
        translate: `${(1 - p) * 80}px 0px`,
        scale: interpolate(p, [0, 1], [0.94, 1]),
        ...style,
      }}
    >
      {children}
    </div>
  );
};

// ── Cuts ─────────────────────────────────────────────────────────────────────
/** Light sweep + flash, used as a TransitionSeries.Overlay on key hard cuts. */
export const SweepOverlay: React.FC = () => {
  const frame = useCurrentFrame();
  const { durationInFrames, width, height } = useVideoConfig();
  const p = interpolate(frame, [0, durationInFrames - 1], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
    easing: EXPO_IN,
  });
  const flash = interpolate(frame, [0, durationInFrames / 2, durationInFrames - 1], [0, 0.22, 0], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  return (
    <AbsoluteFill style={{ pointerEvents: "none" }}>
      <AbsoluteFill style={{ backgroundColor: `hsl(239 100% 90% / ${flash})` }} />
      <div
        style={{
          position: "absolute",
          top: -200,
          left: interpolate(p, [0, 1], [-700, width + 200]),
          width: 420,
          height: height + 400,
          rotate: "18deg",
          background: "linear-gradient(90deg, transparent, hsl(239 100% 85% / 0.35), hsl(258 95% 84% / 0.5), transparent)",
          filter: "blur(30px)",
        }}
      />
    </AbsoluteFill>
  );
};

/** CSS zoom-through transition (no shaders): exiting scene zooms past camera, entering lands from behind. */
const ZoomThrough: React.FC<TransitionPresentationComponentProps<Record<string, never>>> = ({
  children,
  presentationDirection,
  presentationProgress,
}) => {
  const entering = presentationDirection === "entering";
  const scale = entering
    ? interpolate(presentationProgress, [0, 1], [0.86, 1])
    : interpolate(presentationProgress, [0, 1], [1, 1.25]);
  const opacity = entering ? presentationProgress : 1 - presentationProgress;
  return <AbsoluteFill style={{ scale, opacity }}>{children}</AbsoluteFill>;
};

export const zoomThrough = (): TransitionPresentation<Record<string, never>> => ({
  component: ZoomThrough,
  props: {},
});

