// GENERATED by tools/make_vo.py — seconds of speech per voiceover beat (beat-1 … beat-7).
// Voice: af_heart · speed 1.1
export const VO_SECONDS = [3.98, 4.42, 5.29, 6.25, 4.08, 3.3, 2.42] as const;
