// GENERATED by tools/make_music.py — frame map (30 fps) for public/music/syrel-pulse.wav.
// To use another track (Pixabay / YouTube Audio Library), drop it in public/music/ and set
// MUSIC in src/promo/music.ts to its file, BPM and offset (seconds to the first downbeat);
// makeBeatMap() rebuilds this same map from those numbers, assuming the same 16-bar shape.
export const BPM = 120;
export const OFFSET_S = 0;
export const BEAT_FRAMES = 15;
export const BAR_FRAMES = 60;
export const BEATS = [0, 15, 30, 45, 60, 75, 90, 105, 120, 135, 150, 165, 180, 195, 210, 225, 240, 255, 270, 285, 300, 315, 330, 345, 360, 375, 390, 405, 420, 435, 450, 465, 480, 495, 510, 525, 540, 555, 570, 585, 600, 615, 630, 645, 660, 675, 690, 705, 720, 735, 750, 765, 780, 795, 810, 825, 840, 855, 870, 885, 900, 915, 930, 945, 960] as const;
export const BARS = [0, 60, 120, 180, 240, 300, 360, 420, 480, 540, 600, 660, 720, 780, 840, 900, 960] as const; // bar N starts at BARS[N - 1]
export const DROP_1 = 120; // bar 3 — impact + first drop
export const BREAKDOWN = 600; // bar 11
export const BUILD = 660; // bar 12 — snare roll + riser
export const DROP_2 = 720; // bar 13
export const FINAL_HIT = 900; // bar 16 downbeat
export const TRACK_FRAMES = 1005;
