"""Phase 276 (DOCS-03) — the committed OpenAPI snapshot must match the code.

``docs/public/api/openapi.snapshot.json`` is the source the public "Syrel API" reference is
filtered from (``scripts/build-public-openapi.cjs``). If a new endpoint lands and nobody
regenerates the snapshot, the public docs silently describe an older API. This test is the
PRIMARY guard (it rides the mandatory backend unit gate, which runs locally); the
``public-openapi`` CI workflow's ``--check`` is the backstop for the filtered file.

**One home.** The snapshot is generated by ``scripts/export-openapi.py``'s ``build_snapshot()``,
loaded here through ``importlib`` — the test and the export command can never disagree about
how the document is produced. ``build_snapshot`` calls the FastAPI CLASS method
``FastAPI.openapi(app)``, not the canvas-aware instance hook, so the result does not depend on
the live canvas flag or on the database.
"""
import importlib.util
import json
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[3]
_SNAPSHOT = _REPO_ROOT / "docs" / "public" / "api" / "openapi.snapshot.json"
_EXPORT_SCRIPT = _REPO_ROOT / "scripts" / "export-openapi.py"
_REGEN = "backend/venv/Scripts/python scripts/export-openapi.py"


def _load_export_module():
    spec = importlib.util.spec_from_file_location("export_openapi_276", _EXPORT_SCRIPT)
    assert spec is not None and spec.loader is not None, f"cannot load {_EXPORT_SCRIPT}"
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_committed_openapi_snapshot_matches_the_code():
    module = _load_export_module()
    generated = module.build_snapshot()
    committed = json.loads(_SNAPSHOT.read_text(encoding="utf-8"))

    if generated != committed:
        gen_paths, com_paths = set(generated.get("paths", {})), set(committed.get("paths", {}))
        added = sorted(gen_paths - com_paths)
        removed = sorted(com_paths - gen_paths)
        raise AssertionError(
            "docs/public/api/openapi.snapshot.json is stale — the API in code differs from the "
            f"committed snapshot (paths added: {added[:10]}, removed: {removed[:10]}; other "
            f"differences may be in operations or schemas). Regenerate with `{_REGEN}` from the "
            "repo root, then `node scripts/build-public-openapi.cjs` and commit both files."
        )


def test_snapshot_never_contains_test_fixture_routes():
    module = _load_export_module()
    generated = module.build_snapshot()
    assert not [p for p in generated["paths"] if p.startswith("/__test__")]
