"""Phase 139 Plan 02 (SI-02) — description-proposal router owner-scoping / lifecycle tests.

SI-02 wraps the Trigger Tuner's held-out per-provider WINNER in the SI-01
propose -> review-diff -> approve -> immutable-version lifecycle, DESCRIPTION field only. This
is the FIRST place a Tuner winner is drafted through the honest front door (D-08 — replacing the
one-click ``PATCH /skills`` apply), so the owner-scoping gate + the honest-by-construction refusal
+ the no-live-write-on-propose invariant are all load-bearing.

All five tests drive the REAL FastAPI app through the four description-proposal routes with NO live
DB and NO live provider — the proposer IS the Tuner (D-01), so there is nothing to patch: the winner
is READ from a seeded ``tuner_runs`` scoreboard, never generated by an LLM. ``get_current_user`` /
``get_supabase`` are dependency-overridden with the in-memory filtering fake reused from
``test_evals_router`` (it honors ``.eq()`` / ``.in_()`` chains + insert/update so the owner-scoping
404 and the pure-audit reject are MEANINGFUL, not vacuous):

  1. ``test_propose_creates_draft_no_live_write`` (SI-02 SC1 / D-01/D-06 / V1): propose from a
     NON-baseline held-out winner drafts a ``kind='description'`` ``status='proposed'`` row whose
     ``proposed_description`` == the winner + ``base_description`` == the skill's CURRENT description,
     and ``skills.description`` is UNCHANGED (no live write). The persisted ``scoreboard_snapshot``
     carries the LITERAL top-level keys ``{winner, baseline, run_id}`` (not a ``candidates``/
     ``winner_index`` blob) — pinning the writer half of the 139-04 ``DescriptionScoreboardSnapshot``.
  2. ``test_baseline_winner_refuses_propose`` (D-02 / V2): when the held-out WINNER IS the baseline,
     propose returns 400 "nothing to propose" and creates ZERO ``skill_proposals`` rows.
  3. ``test_approve_writes_desc_and_version`` (D-04/D-07 / V3): approve writes ``skills.description``,
     captures EXACTLY ONE new immutable ``skill_versions`` row (the fake mirrors the 079/132 trigger),
     links ``new_skill_version_id`` from ``MAX(version_number)``, and flips to ``promoted``.
  4. ``test_reject_is_pure_audit`` (D-05 / V4): reject flips to ``rejected`` with
     ``new_skill_version_id`` NULL, no description/version mutation — and is KIND-GATED (an
     ``instruction`` proposal sent to the description-reject route 404s and is NOT flipped).
  5. ``test_cross_user_404`` (T-139-04/05 IDOR / V5): a non-owner calling propose/approve/reject each
     gets 404 (never 403); no IDOR write lands.

Reuses ``_FilterSupabase`` / ``_FilterTable`` / ``_override`` / ``_clear_overrides`` from
``test_evals_router`` so the fake store semantics stay identical to the sibling proposal-router tests.
"""
from types import SimpleNamespace
from uuid import uuid4

import httpx
import pytest
from httpx import ASGITransport

from tests.test_evals_router import (
    _FilterSupabase,
    _FilterTable,
    _clear_overrides,
    _override,
)

OWNER = {"id": "00000000-0000-0000-0000-000000000001", "email": "owner@example.com"}
OTHER_USER = {"id": "00000000-0000-0000-0000-000000000099", "email": "other@example.com"}

_H = {"Authorization": "Bearer test"}

_BASE_DESC = "Use this skill to summarize documents."
_BETTER_DESC = "Use this skill to summarize long documents into concise, cited bullet points."


# ── A store-preserving fake that ALSO mirrors the 079/132 capture_skill_version trigger ──────
# The real approve route writes ONLY ``skills.description`` and lets the DB trigger capture the
# immutable version (source='manual', no draft INSERT — D-07). The plain ``_FilterSupabase`` has no
# triggers, so this thin subclass fires the version-capture on any ``skills`` UPDATE that changes
# ``description`` — appending EXACTLY ONE ``skill_versions`` row (version_number = max+1). That makes
# ``test_approve_writes_desc_and_version`` assert one-version-not-two (RESEARCH Pitfall 2) faithfully.
class _TriggerTable(_FilterTable):
    def execute(self, *a, **k):
        res = super().execute(*a, **k)
        if (
            self._op == "update"
            and self.name == "skills"
            and isinstance(self._payload, dict)
            and "description" in self._payload
            and res.data
        ):
            versions = self.store.setdefault("skill_versions", [])
            for skill in res.data:
                owned = [v for v in versions if str(v.get("skill_id")) == str(skill.get("id"))]
                next_num = (max((v.get("version_number") or 0) for v in owned) if owned else 0) + 1
                versions.append(
                    {
                        "id": str(uuid4()),
                        "skill_id": skill.get("id"),
                        "user_id": skill.get("user_id"),
                        "version_number": next_num,
                        "name": skill.get("name") or "",
                        "description": skill.get("description"),
                        "instructions": "",
                        "source": "manual",
                    }
                )
        return res


class _TriggerSupabase(_FilterSupabase):
    def table(self, name):
        return _TriggerTable(self.store, name)


def _seed(*, winner_is_baseline=False, run_id="tuner-run-abc", proposal_status=None,
          proposal_kind="description", proposal_id=None):
    """Build an in-memory store: an OWNER skill + its base version + a completed ``tuner_runs`` row
    whose scoreboard's held-out winner is (by default) a NON-baseline rewrite — the minimum the
    propose route reads. Optionally seed ONE proposal row (for approve / reject / cross-user paths).
    Returns (store, ids)."""
    skill_id = str(uuid4())
    version_id = str(uuid4())
    tuner_run_id = str(uuid4())

    cells = [
        {"provider": "openai", "model": "gpt-5.1", "measured": True, "fires": 4, "no_false": 3},
        {"provider": "anthropic", "model": "claude-haiku-4-5", "measured": True, "fires": 4, "no_false": 3},
    ]
    baseline_cand = {"index": 0, "description": _BASE_DESC, "is_baseline": True,
                     "held_out_score": 0.55, "cells": cells}
    rewrite_cand = {"index": 1, "description": _BETTER_DESC, "is_baseline": False,
                    "held_out_score": 0.92, "cells": cells}
    if winner_is_baseline:
        winner_index, winner_description = 0, _BASE_DESC
    else:
        winner_index, winner_description = 1, _BETTER_DESC
    scoreboard = {
        "skill_id": skill_id,
        "candidates": [baseline_cand, rewrite_cand],
        "winner_index": winner_index,
        "winner_description": winner_description,
    }

    store = {
        "skills": [
            {"id": skill_id, "name": "Summarizer", "description": _BASE_DESC, "user_id": OWNER["id"]}
        ],
        "skill_versions": [
            {
                "id": version_id,
                "skill_id": skill_id,
                "user_id": OWNER["id"],
                "version_number": 1,
                "name": "Summarizer",
                "description": _BASE_DESC,
                "instructions": "BASE INSTRUCTIONS",
                "source": "manual",
            }
        ],
        "tuner_runs": [
            {
                "id": tuner_run_id,
                "skill_id": skill_id,
                "user_id": OWNER["id"],
                "run_id": run_id,
                "scoreboard": scoreboard,
                "builder_model": "gpt-5.1",
                "target_count": 2,
                "case_count": 6,
                "updated_at": "2026-07-06T00:00:00Z",
            }
        ],
        "skill_proposals": [],
    }
    if proposal_status is not None:
        pid = proposal_id or str(uuid4())
        is_desc = proposal_kind == "description"
        store["skill_proposals"].append(
            {
                "id": pid,
                "skill_id": skill_id,
                "base_skill_version_id": version_id,
                "new_skill_version_id": None,
                "re_eval_run_id": None,
                "source_eval_run_id": None,
                "source_tuner_run_id": tuner_run_id if is_desc else None,
                "user_id": OWNER["id"],
                "kind": proposal_kind,
                "proposed_instructions": None if is_desc else "PROPOSED BODY",
                "proposed_description": _BETTER_DESC if is_desc else None,
                "scoreboard_snapshot": (
                    {"winner": rewrite_cand, "baseline": baseline_cand, "run_id": run_id}
                    if is_desc
                    else None
                ),
                "rationale": "",
                "evidence_summary": "",
                "status": proposal_status,
                "override_forced": False,
                "created_at": "2026-07-06T00:00:00Z",
                "updated_at": "2026-07-06T00:00:00Z",
            }
        )
    return store, SimpleNamespace(
        skill_id=skill_id, version_id=version_id, tuner_run_id=tuner_run_id, run_id=run_id
    )


@pytest.mark.asyncio
async def test_propose_creates_draft_no_live_write():
    """SI-02 SC1 / D-01/D-06 (V1): OWNER proposes from a NON-baseline held-out winner -> a
    ``kind='description'`` ``proposed`` draft; the live ``skills.description`` is UNCHANGED (the
    proposer never edits a live skill). The persisted ``scoreboard_snapshot`` has the LITERAL
    ``{winner, baseline, run_id}`` top-level keys — the 139-04 writer contract."""
    from app.main import app

    store, ids = _seed(winner_is_baseline=False)
    sb = _FilterSupabase(store)

    _override(app, user=OWNER, supabase=sb)
    try:
        async with httpx.AsyncClient(
            transport=ASGITransport(app=app), base_url="http://test"
        ) as c:
            resp = await c.post(
                f"/skills/{ids.skill_id}/description-proposals",
                json={"run_id": ids.run_id},
                headers=_H,
            )
    finally:
        _clear_overrides(app)

    assert resp.status_code in (200, 201), f"propose {resp.status_code}: {resp.text}"
    body = resp.json()
    assert body["kind"] == "description"
    assert body["status"] == "proposed"
    assert body["proposed_description"] == _BETTER_DESC
    # base_description is the skill's CURRENT live description (the diff base) — hydrated, not stored.
    assert body["base_description"] == _BASE_DESC
    # No live write: the skill's description row is UNCHANGED after propose.
    assert store["skills"][0]["description"] == _BASE_DESC, "propose must NOT write the live skill"

    # A durable proposed row landed via the service-role insert, owner-stamped, provenance-linked.
    proposals = sb.store.get("skill_proposals", [])
    assert len(proposals) == 1
    row = proposals[0]
    assert row["kind"] == "description"
    assert row["status"] == "proposed"
    assert row["user_id"] == OWNER["id"]
    assert row["proposed_description"] == _BETTER_DESC
    assert str(row["source_tuner_run_id"]) == ids.tuner_run_id

    # The snapshot has the LITERAL {winner, baseline, run_id} top-level keys (writer half of the
    # 139-04 DescriptionScoreboardSnapshot contract) — NOT a raw candidates/winner_index blob.
    snap = row["scoreboard_snapshot"]
    assert set(snap.keys()) == {"winner", "baseline", "run_id"}, snap
    assert "candidates" not in snap and "winner_index" not in snap
    assert snap["run_id"] == ids.run_id
    assert snap["winner"]["is_baseline"] is False
    assert snap["baseline"]["is_baseline"] is True
    # And the serialized response carries the same snapshot (declared on the model, not stripped).
    assert set(body["scoreboard_snapshot"].keys()) == {"winner", "baseline", "run_id"}


@pytest.mark.asyncio
async def test_baseline_winner_refuses_propose():
    """D-02 (V2): when the held-out WINNER IS the baseline, propose returns 400 "nothing to propose"
    and creates ZERO rows — honest-by-construction (the proposer never fabricates a diff)."""
    from app.main import app

    store, ids = _seed(winner_is_baseline=True)
    sb = _FilterSupabase(store)

    _override(app, user=OWNER, supabase=sb)
    try:
        async with httpx.AsyncClient(
            transport=ASGITransport(app=app), base_url="http://test"
        ) as c:
            resp = await c.post(
                f"/skills/{ids.skill_id}/description-proposals",
                json={"run_id": ids.run_id},
                headers=_H,
            )
    finally:
        _clear_overrides(app)

    assert resp.status_code == 400, f"baseline-winner propose {resp.status_code}: {resp.text}"
    assert "nothing to propose" in resp.text.lower()
    assert len(store.get("skill_proposals", [])) == 0, "baseline-winner must create ZERO rows"


@pytest.mark.asyncio
async def test_approve_writes_desc_and_version():
    """D-04/D-07 (V3): approve writes the LIVE description, the trigger captures EXACTLY ONE new
    immutable version, ``new_skill_version_id`` links to MAX(version_number), status -> promoted."""
    from app.main import app

    pid = str(uuid4())
    store, ids = _seed(proposal_status="proposed", proposal_id=pid)
    sb = _TriggerSupabase(store)  # mirrors the 079/132 capture_skill_version trigger
    versions_before = len(store["skill_versions"])

    _override(app, user=OWNER, supabase=sb)
    try:
        async with httpx.AsyncClient(
            transport=ASGITransport(app=app), base_url="http://test"
        ) as c:
            resp = await c.post(
                f"/skills/{ids.skill_id}/description-proposals/{pid}/approve",
                headers=_H,
            )
    finally:
        _clear_overrides(app)

    assert resp.status_code == 200, f"approve {resp.status_code}: {resp.text}"
    body = resp.json()
    assert body["status"] == "promoted"
    # The live skill description was written to the proposed (winning) description.
    assert store["skills"][0]["description"] == _BETTER_DESC
    # EXACTLY ONE new immutable version captured by the trigger (no double-capture — Pitfall 2).
    assert len(store["skill_versions"]) == versions_before + 1
    new_ver = max(store["skill_versions"], key=lambda v: v["version_number"])
    assert body["new_skill_version_id"] == new_ver["id"], "must link MAX(version_number) read-back"
    # The proposal row promoted + linked, owner-scoped.
    prop = next(p for p in store["skill_proposals"] if p["id"] == pid)
    assert prop["status"] == "promoted"
    assert str(prop["new_skill_version_id"]) == new_ver["id"]


@pytest.mark.asyncio
async def test_reject_is_pure_audit():
    """D-05 (V4): reject flips to 'rejected' with new_skill_version_id NULL, no description/version
    mutation; and is KIND-GATED — an instruction proposal sent to the description-reject route 404s
    and is NOT flipped."""
    from app.main import app

    # (a) description reject is a pure audit flip.
    pid = str(uuid4())
    store, ids = _seed(proposal_status="proposed", proposal_id=pid)
    sb = _TriggerSupabase(store)  # if reject wrongly wrote skills, the trigger would add a version
    versions_before = len(store["skill_versions"])
    skills_before = [dict(s) for s in store["skills"]]

    _override(app, user=OWNER, supabase=sb)
    try:
        async with httpx.AsyncClient(
            transport=ASGITransport(app=app), base_url="http://test"
        ) as c:
            resp = await c.post(
                f"/skills/{ids.skill_id}/description-proposals/{pid}/reject",
                headers=_H,
            )
    finally:
        _clear_overrides(app)

    assert resp.status_code == 200, f"reject {resp.status_code}: {resp.text}"
    body = resp.json()
    assert body["status"] == "rejected"
    assert body["new_skill_version_id"] is None
    prop = next(p for p in store["skill_proposals"] if p["id"] == pid)
    assert prop["status"] == "rejected"
    assert prop.get("new_skill_version_id") is None
    assert len(store["skill_versions"]) == versions_before, "reject must NOT add a version"
    assert [dict(s) for s in store["skills"]] == skills_before, "reject must NOT write skills"

    # (b) KIND GUARD: an instruction proposal sent to the description-reject route 404s + is NOT flipped.
    ipid = str(uuid4())
    store2, ids2 = _seed(proposal_status="proposed", proposal_id=ipid, proposal_kind="instruction")
    sb2 = _FilterSupabase(store2)

    _override(app, user=OWNER, supabase=sb2)
    try:
        async with httpx.AsyncClient(
            transport=ASGITransport(app=app), base_url="http://test"
        ) as c:
            resp2 = await c.post(
                f"/skills/{ids2.skill_id}/description-proposals/{ipid}/reject",
                headers=_H,
            )
    finally:
        _clear_overrides(app)

    assert resp2.status_code == 404, f"wrong-kind reject must 404, got {resp2.status_code}"
    iprop = next(p for p in store2["skill_proposals"] if p["id"] == ipid)
    assert iprop["status"] == "proposed", "the instruction proposal must NOT be flipped"


@pytest.mark.asyncio
async def test_cross_user_404():
    """T-139-04/05 (V5 IDOR): OTHER_USER propose / approve / reject against OWNER's skill + proposal
    each return 404 (never 403); a malformed skill_id also 404s; NO IDOR write lands."""
    from app.main import app

    pid = str(uuid4())
    store, ids = _seed(proposal_status="proposed", proposal_id=pid)
    sb = _TriggerSupabase(store)

    _override(app, user=OTHER_USER, supabase=sb)
    try:
        async with httpx.AsyncClient(
            transport=ASGITransport(app=app), base_url="http://test"
        ) as c:
            propose_resp = await c.post(
                f"/skills/{ids.skill_id}/description-proposals",
                json={"run_id": ids.run_id},
                headers=_H,
            )
            approve_resp = await c.post(
                f"/skills/{ids.skill_id}/description-proposals/{pid}/approve",
                headers=_H,
            )
            reject_resp = await c.post(
                f"/skills/{ids.skill_id}/description-proposals/{pid}/reject",
                headers=_H,
            )
            malformed_resp = await c.post(
                "/skills/not-a-uuid/description-proposals",
                json={"run_id": ids.run_id},
                headers=_H,
            )
    finally:
        _clear_overrides(app)

    assert propose_resp.status_code == 404, f"cross-user propose {propose_resp.status_code}"
    assert approve_resp.status_code == 404, f"cross-user approve {approve_resp.status_code}"
    assert reject_resp.status_code == 404, f"cross-user reject {reject_resp.status_code}"
    assert malformed_resp.status_code == 404, f"malformed skill_id {malformed_resp.status_code}"

    # No IDOR write landed: propose inserted nothing, approve/reject did NOT touch the OWNER row/skill.
    proposals = store.get("skill_proposals", [])
    assert len(proposals) == 1, "cross-user propose must NOT insert a row"
    assert proposals[0]["status"] == "proposed", "cross-user approve/reject must NOT flip status"
    assert proposals[0]["user_id"] == OWNER["id"]
    assert store["skills"][0]["description"] == _BASE_DESC, "cross-user approve must NOT write skills"
