-- Phase 14: Code Execution Sandbox tables + storage bucket

-- code_executions: logs each execute_code invocation
CREATE TABLE IF NOT EXISTS public.code_executions (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  thread_id   uuid NOT NULL REFERENCES public.threads(id) ON DELETE CASCADE,
  user_id     uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  code        text NOT NULL,
  exit_code   integer,
  duration_ms integer,
  created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.code_executions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own executions"
  ON public.code_executions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own executions"
  ON public.code_executions FOR INSERT WITH CHECK (auth.uid() = user_id);

-- sandbox_files: metadata for files generated by code execution
CREATE TABLE IF NOT EXISTS public.sandbox_files (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  execution_id    uuid NOT NULL REFERENCES public.code_executions(id) ON DELETE CASCADE,
  user_id         uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  filename        text NOT NULL,
  storage_path    text NOT NULL,
  file_size       bigint NOT NULL DEFAULT 0,
  created_at      timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.sandbox_files ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own sandbox files"
  ON public.sandbox_files FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own sandbox files"
  ON public.sandbox_files FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Storage bucket for sandbox output files (private)
INSERT INTO storage.buckets (id, name, public)
VALUES ('sandbox-outputs', 'sandbox-outputs', false)
ON CONFLICT (id) DO NOTHING;
