// GENERATED by tools/make_vo.py --clips — seconds of speech per feature clip.
// Voice: af_heart · speed 1.1
export const CLIP_VO_SECONDS = { chat: 6.5, library: 7.96, workflows: 6.83, connections: 7.34, experts: 5.69, admin: 7.17 } as const;
export type ClipId = keyof typeof CLIP_VO_SECONDS;
